import { nanoid } from "nanoid";
import type { Game } from "@/lib/types";

export function createDemoGame(): Game {
  return {
    id: nanoid(),
    name: "Esimerkki: Suomi-visailu",
    createdAt: new Date().toISOString(),
    teams: [],
    categories: [
      {
        id: nanoid(),
        name: "SUOMEN HISTORIA",
        questions: [
          {
            id: nanoid(),
            points: 100,
            answer: "Suomi itsenäistyi tänä vuonna",
            question: "Mikä on 1917?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 200,
            answer: "Hän toimi Suomen ensimmäisenä presidenttinä",
            question: "Kuka on Kaarlo Juho Ståhlberg?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 300,
            answer: "Suomen ja Neuvostoliiton välinen talvisota alkoi tänä vuonna",
            question: "Mikä on 1939?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 400,
            answer: "Suomi liittyi Euroopan unioniin tänä vuonna",
            question: "Mikä on 1995?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 500,
            answer: "Tämä kaupunki toimi Suomen pääkaupunkina ennen Helsinkiä",
            question: "Mikä on Turku?",
            isPlayed: false,
          },
        ],
      },
      {
        id: nanoid(),
        name: "SUOMEN LUONTO",
        questions: [
          {
            id: nanoid(),
            points: 100,
            answer: "Suomen kansallislintu",
            question: "Mikä on laulujoutsen?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 200,
            answer: "Suomen suurin järvi",
            question: "Mikä on Saimaa?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 300,
            answer: "Suomen korkein tunturi",
            question: "Mikä on Halti?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 400,
            answer: "Tätä puuta on eniten Suomen metsissä",
            question: "Mikä on mänty?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 500,
            answer: "Suomessa on näitä järviä noin 188 000",
            question: "Mitä ovat järvet?",
            isPlayed: false,
          },
        ],
      },
      {
        id: nanoid(),
        name: "SUOMALAISET URHEILU",
        questions: [
          {
            id: nanoid(),
            points: 100,
            answer: "Suomen kuuluisin formula-kuljettaja, seitsemän MM-titteliä",
            question: "Kuka on Kimi Räikkönen?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 200,
            answer: "Laji, jossa Suomi on voittanut eniten olympiamitaleita",
            question: "Mikä on yleisurheilu?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 300,
            answer: "Suomalainen pesäpallo on saanut vaikutteita tästä amerikkalaisesta lajista",
            question: "Mikä on baseball?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 400,
            answer: "Tämä suomalainen hiihtäjä voitti viisi olympiakultaa vuosina 1984–1994",
            question: "Kuka on Marja-Liisa Kirvesniemi?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 500,
            answer: "Ensimmäinen suomalainen jääkiekon MM-kultamitali voitettiin tänä vuonna",
            question: "Mikä on 1995?",
            isPlayed: false,
          },
        ],
      },
      {
        id: nanoid(),
        name: "SUOMALAINEN KULTTUURI",
        questions: [
          {
            id: nanoid(),
            points: 100,
            answer: "Suomen kansalliseepos",
            question: "Mikä on Kalevala?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 200,
            answer: "Tämä suomalainen säveltäjä kirjoitti Finlandian",
            question: "Kuka on Jean Sibelius?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 300,
            answer: "Suomalainen arkkitehti, tunnettu mm. Finlandiatalo-suunnittelusta",
            question: "Kuka on Alvar Aalto?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 400,
            answer: "Tämä suomalainen kirjailija kirjoitti Seitsemän veljestä",
            question: "Kuka on Aleksis Kivi?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 500,
            answer: "Mummi ja möhkö sekä Muumipappa ovat hahmoja tästä suomalaisesta sarjasta",
            question: "Mikä on Muumilaakso?",
            isPlayed: false,
          },
        ],
      },
      {
        id: nanoid(),
        name: "MAANTIETO",
        questions: [
          {
            id: nanoid(),
            points: 100,
            answer: "Suomen pääkaupunki",
            question: "Mikä on Helsinki?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 200,
            answer: "Suomen pisin joki",
            question: "Mikä on Kemijoki?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 300,
            answer: "Suomella on maaraja näiden kolmen maan kanssa",
            question: "Mitkä ovat Ruotsi, Norja ja Venäjä?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 400,
            answer: "Suomen väkiluku on noin tämän verran",
            question: "Mikä on 5,5 miljoonaa?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 500,
            answer: "Tämä Suomen maakunta on pinta-alaltaan suurin",
            question: "Mikä on Lappi?",
            isPlayed: false,
          },
        ],
      },
      {
        id: nanoid(),
        name: "SEKALAISTA",
        questions: [
          {
            id: nanoid(),
            points: 100,
            answer: "Suomalainen saunaperinne lisättiin tähän UNESCOn listaan vuonna 2020",
            question: "Mikä on aineettoman kulttuuriperinnön luettelo?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 200,
            answer: "Tämä suomalainen peli on yksi maailman myydyimmistä mobiilipeleistä",
            question: "Mikä on Angry Birds?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 300,
            answer: "Suomalaiset juovat maailman eniten tätä juomaa per henkilö",
            question: "Mikä on kahvi?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 400,
            answer: "Tämä suomalainen keksintö mullisti matkaviestinnän 1990-luvulla",
            question: "Mikä on Nokia-puhelin?",
            isPlayed: false,
          },
          {
            id: nanoid(),
            points: 500,
            answer: "Suomessa järjestetään vuosittain tämä erikoinen MM-kilpailu, jossa kannetaan vaimoa",
            question: "Mikä on eukonkanto?",
            isPlayed: false,
          },
        ],
      },
    ],
  };
}
